tap "golangci/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "oven-sh/bun"
tap "rcmdnk/file"
tap "sanemat/font"
brew "pycparser"
brew "cffi"
brew "docutils"
brew "python@3.11"
brew "awscli"
brew "cmake"
brew "direnv"
brew "libgit2"
brew "exa"
brew "gh"
brew "git"
brew "node"
brew "gitmoji"
brew "goenv"
brew "jq"
brew "mas"
brew "mysql-client"
brew "mydumper"
brew "protobuf"
brew "mysql"
brew "neovim"
brew "pnpm"
brew "poetry"
brew "pyenv"
brew "python@3.10"
brew "rbenv"
brew "rust", link: false
brew "rustup-init"
brew "rye"
brew "shellcheck"
brew "starship"
brew "tmux"
brew "tree"
brew "wget"
brew "golangci/tap/golangci-lint"
brew "oven-sh/bun/bun"
brew "rcmdnk/file/brew-file"
cask "alfred", args: { appdir: "/Applications" }
cask "cheatsheet", args: { appdir: "/Applications" }
cask "deepl", args: { appdir: "/Applications" }
cask "discord", args: { appdir: "/Applications" }
cask "docker", args: { appdir: "/Applications" }
cask "figma", args: { appdir: "/Applications" }
cask "font-agave-nerd-font"
cask "font-fira-mono-nerd-font"
cask "font-hack-nerd-font"
cask "font-hackgen-nerd"
cask "goland", args: { appdir: "/Applications" }
cask "google-chrome", args: { appdir: "/Applications" }
cask "google-drive", args: { appdir: "/Applications" }
cask "intellij-idea", args: { appdir: "/Applications" }
cask "iterm2"
cask "miniconda"
cask "ngrok", args: { appdir: "/Applications" }
cask "notion", args: { appdir: "/Applications" }
cask "pgadmin4"
cask "postman", args: { appdir: "/Applications" }
cask "pycharm", args: { appdir: "/Applications" }
cask "raycast"
cask "session-manager-plugin"
cask "slack", args: { appdir: "/Applications" }
cask "sourcetree", args: { appdir: "/Applications" }
cask "visual-studio-code", args: { appdir: "/Applications" }
cask "warp", args: { appdir: "/Applications" }
cask "zoom", args: { appdir: "/Applications" }
vscode "aprilandjan.ascii-tree-generator"
vscode "arjun.swagger-viewer"
vscode "azemoh.one-monokai"
vscode "bierner.markdown-mermaid"
vscode "burkeholland.simple-react-snippets"
vscode "charliermarsh.ruff"
vscode "chris-hayes.chatgpt-reborn"
vscode "christian-kohler.npm-intellisense"
vscode "christian-kohler.path-intellisense"
vscode "codezombiech.gitignore"
vscode "cweijan.dbclient-jdbc"
vscode "cweijan.vscode-database-client2"
vscode "dbaeumer.vscode-eslint"
vscode "dracula-theme.theme-dracula"
vscode "dsznajder.es7-react-js-snippets"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "fabiospampinato.vscode-monokai-night"
vscode "figma.figma-vscode-extension"
vscode "formulahendry.auto-rename-tag"
vscode "gencay.vscode-chatgpt"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "golang.go"
vscode "graphql.vscode-graphql"
vscode "graphql.vscode-graphql-syntax"
vscode "hediet.vscode-drawio"
vscode "infeng.vscode-react-typescript"
vscode "jakob101.relativepath"
vscode "jasonnutter.search-node-modules"
vscode "jawandarajbir.react-vscode-extension-pack"
vscode "jprestidge.theme-material-theme"
vscode "kingwl.ts-react-hooks-tools"
vscode "kiranshah.chatgpt-helper"
vscode "mhutchie.git-graph"
vscode "monokai.theme-monokai-pro-vscode"
vscode "mosapride.zenkaku"
vscode "ms-azuretools.vscode-docker"
vscode "ms-ceintl.vscode-language-pack-ja"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-server"
vscode "ms-vsliveshare.vsliveshare"
vscode "oderwat.indent-rainbow"
vscode "orsenkucher.vscode-graphql"
vscode "pkief.material-icon-theme"
vscode "pmneo.tsimporter"
vscode "prisma.prisma"
vscode "qwtel.sqlite-viewer"
vscode "rangav.vscode-thunder-client"
vscode "redhat.vscode-yaml"
vscode "ritwickdey.liveserver"
vscode "ryu1kn.partial-diff"
vscode "sburg.vscode-javascript-booster"
vscode "shopify.ruby-lsp"
vscode "steoates.autoimport"
vscode "streetsidesoftware.code-spell-checker"
vscode "styled-components.vscode-styled-components"
vscode "techtrain.railway-vscode"
vscode "tinkertrain.theme-panda"
vscode "twxs.cmake"
vscode "vscode-icons-team.vscode-icons"
vscode "vscodevim.vim"
vscode "withfig.fig"
vscode "xabikos.javascriptsnippets"
vscode "xabikos.reactsnippets"
vscode "yoavbls.pretty-ts-errors"
